### ISSUE TITLE
Opening/Closing Category Side Panel JavaScript null reference error 

### ISSUE THREAD

**Issue by TyreKing** [chingu-voyages/v42-toucans-team-04#16]
**Describe the problem**
When opening and closing the category side panel, the javaScript is displaying an null reference error. 

**Expected behavior**
Error should not display when in the console when opening/closing the categories sidepanel.

**To Reproduce**
1. Run the solution and press F12 to open the devTools
2. Click on 'Console' tab in the devTools
3. Click on the Categories menu option in the top nav page on the webpage
4. Observe the console display the javaScript error.

**Screenshots**
![image](https://user-images.githubusercontent.com/38078087/212721228-131d5b91-5ba1-4cae-b9c8-2ac6f688ba1b.png)

**Comment by jtaylor1204** [comment]
Resolved
