### ISSUE TITLE
CSS Scales Down Too Much

### ISSUE THREAD

**Issue by TyreKing** [chingu-voyages/v42-toucans-team-04#21]
**Describe the problem**
The Webpage Scales down too much and looks small on larger screens

**Expected behavior**
Webpage should should have consistent sizing across all screens

![image](https://user-images.githubusercontent.com/38078087/213848301-57b879e3-7026-4290-8c91-b27d498f5c47.png)

**Comment by jtaylor1204** [comment]
Check out the recent merge and tell me what you think
